export const LOGIN_USER = "LOGIN_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const LOADING_STATE_TOGGLER = "LOADING_STATE_TOGGLER";
export const SET_CURRENT_NAV_ITEM = "SET_CURRENT_NAV_ITEM";
export const TOGGLE_ADD_ARTIST_DIALOG = "TOGGLE_ADD_ARTIST_DIALOG";