apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: obs-jenkins-pv
  namespace: jenkins
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: do-block-storage