version: 2.1

workflows:
    build:
        jobs:
            - build
                context: obs-context

jobs:
    build:
        docker:
            - image: circleci/buildpack-deps:stretch
        steps:
            - run: echo $GITHUB_USERNAME

