apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: letsencrypt-openbeats-dns
spec:
  acme:
    email: grthayalan18@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-openbeats-dns
    solvers:
      - dns01:
          cnameStrategy: Follow
          digitalocean:
            tokenSecretRef:
              name: digitalocean-dns
              key: access-token
