apiVersion: apps/v1
kind: Deployment
metadata:
  name: obs-downcc
spec:
  replicas: 1
  selector:
    matchLabels:
      type: backend
      service: obs-downcc
  template:
    metadata:
      labels:
        type: backend
        service: obs-downcc
    spec:
      containers:
      - name: container
        image: thayalangr/obs-downcc:latest
        env:
        - name: DB
          value: obs-db:27017