apiVersion: apps/v1
kind: Deployment
metadata:
  name: obs-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      type: frontend
      service: obs-frontend
  template:
    metadata:
      labels:
        type: frontend
        service: obs-frontend
    spec:
      containers:
      - name: ui
        image: thayalangr/obs-webc
        # readinessProbe:
        #   httpGet:
        #     path: /
        #     port: 3000
        #   periodSeconds: 1
        # livenessProbe:
        #   httpGet:
        #     path: /
        #     port: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: obs-frontend
spec:
  type: NodePort
  ports:
  - port: 3000
  selector:
    type: frontend
    service: obs-frontend
