apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-deployment
  namespace: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
        - name: jenkins
          image: kmlaydin/modified-jenkins
          ports:
            - containerPort: 8080
          env:
            - name: DOCKER_HOST
              value: tcp://localhost:2375
          volumeMounts:
            - name: jenkins-persistent-storage
              mountPath: /var/jenkins_home
        - name: dockerindocker
          image: docker:18.05-dind
          securityContext:
            privileged: true
          volumeMounts:
            - name: dind-persistent-storage
              mountPath: /var/lib/docker
      initContainers:
        - name: jenkins-data-permission-fix
          image: busybox
          command: ["/bin/chmod", "-R", "777", "/data"]
          volumeMounts:
            - name: jenkins-persistent-storage
              mountPath: /data
        - name: dind-data-permission-fix
          image: busybox
          command: ["/bin/chmod", "-R", "777", "/data"]
          volumeMounts:
            - name: dind-persistent-storage
              mountPath: /data
      volumes:
        - name: jenkins-persistent-storage
          persistentVolumeClaim:
            claimName: obs-jenkins-pv
        - name: dind-persistent-storage
          persistentVolumeClaim:
            claimName: obs-dind-pv