apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: webc
spec:
  replicas: 2
  selector:
    matchLabels:
      type: frontend
      service: webc
  template:
    metadata:
      labels:
        type: frontend
        service: webc
    spec:
      containers:
      - name: ui
        image: thayalangr/obs-webc 
      readinessProbe:
        httpGet:
          path: /
          port: 3000
        periodSeconds: 1
      livenessProbe:
        httpGet:
          path: /
          port: 3000