name: clientapp

on:
  push:
    branches: 
      - production
      - staging
    paths:
      - services/clientapp/**
      
env: 
  SERVICE_PATH: services/clientapp
  DOCKER_REPO_NAME: thayalangr/obs-clientapp
  K8S_DEPLOYMENT_FILE_PATH: k8s/deployments/clientapp.yml
  K8S_DEPLOYMENT_NAME: deployments/obs-clientapp
  PRODUCTION_ING_PATH: k8s/ingress/production-ingress.yml
  STAGING_ING_PATH: k8s/ingress/staging-ingress.yml
  K8S_REDIS_DEPLOYMENT_FILE_PATH: k8s/deployments/redis.yml

jobs:
  production:
    if: github.ref == 'refs/heads/production'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Build and push Docker Image
      uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ${{ env.DOCKER_REPO_NAME }}
        tags: ${{ github.sha }} 
        path: ${{ env.SERVICE_PATH }}

    - name: k8s Check and Apply New Redis
      uses: actions-hub/kubectl@master
      env:
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG_DATA }}
      with:
        args: apply -f ${{ env.K8S_REDIS_DEPLOYMENT_FILE_PATH }} -n default

    - name: k8s Check and Apply New Deployment
      uses: actions-hub/kubectl@master
      env:
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG_DATA }}
      with:
        args: apply -f ${{ env.K8S_DEPLOYMENT_FILE_PATH }} -n default

    - name: k8s Update Deployment
      uses: actions-hub/kubectl@master
      env:
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG_DATA }}
      with:
        args: set image ${{ env.K8S_DEPLOYMENT_NAME }} container=${{ env.DOCKER_REPO_NAME }}:${{ github.sha }} -n default

    - name: k8s Check and Apply New Ingress
      uses: actions-hub/kubectl@master
      env:
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG_DATA }}
      with:
        args: apply -f ${{ env.PRODUCTION_ING_PATH }} -n default
        
  staging:
    if: github.ref == 'refs/heads/staging'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Build and push Docker Image
      uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ${{ env.DOCKER_REPO_NAME }}
        tags: ${{ github.sha }} 
        path: ${{ env.SERVICE_PATH }}

    - name: k8s Check and Apply New Redis
      uses: actions-hub/kubectl@master
      env:
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG_DATA }}
      with:
        args: apply -f ${{ env.K8S_REDIS_DEPLOYMENT_FILE_PATH }} -n staging

    - name: k8s Check and Apply New Deployment
      uses: actions-hub/kubectl@master
      env:
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG_DATA }}
      with:
        args: apply -f ${{ env.K8S_DEPLOYMENT_FILE_PATH }} -n staging

    - name: k8s Update Deployment
      uses: actions-hub/kubectl@master
      env:
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG_DATA }}
      with:
        args: set image ${{ env.K8S_DEPLOYMENT_NAME }} container=${{ env.DOCKER_REPO_NAME }}:${{ github.sha }} -n staging

    - name: k8s Check and Apply New Ingress
      uses: actions-hub/kubectl@master
      env:
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG_DATA }}
      with:
        args: apply -f ${{ env.STAGING_ING_PATH }} -n staging